version: '3.7'
services:
  postgresql:
    container_name: na-slet-postgresql
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
  migrator:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgresql
