"""empty message

Revision ID: 193dc7674ad6
Revises: 01f452b544ab
Create Date: 2023-01-24 08:46:18.759463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193dc7674ad6'
down_revision = '01f452b544ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middle_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'middle_name')
    # ### end Alembic commands ###
