"""empty message

Revision ID: af9cac1f0709
Revises: 9a368348329f
Create Date: 2023-02-04 16:45:18.726037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9cac1f0709'
down_revision = '9a368348329f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix__channels__creator_id'), 'channels', ['creator_id'], unique=False)
    op.create_index('credentials_user_credential_type_idx', 'credentials', ['user_id', 'credential_type'], unique=True)
    op.create_index(op.f('ix__credentials__user_id'), 'credentials', ['user_id'], unique=False)
    op.create_index(op.f('ix__events__category_type'), 'events', ['category_type'], unique=False)
    op.create_index(op.f('ix__events__creator_id'), 'events', ['creator_id'], unique=False)
    op.create_index(op.f('ix__events__end_date'), 'events', ['end_date'], unique=False)
    op.create_index(op.f('ix__events__event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix__events__reg_end_date'), 'events', ['reg_end_date'], unique=False)
    op.create_index(op.f('ix__events__start_date'), 'events', ['start_date'], unique=False)
    op.create_index('favourites_user_event_idx', 'favourites', ['user_id', 'event_id'], unique=True)
    op.create_index(op.f('ix__favourites__event_id'), 'favourites', ['event_id'], unique=False)
    op.create_index(op.f('ix__favourites__user_id'), 'favourites', ['user_id'], unique=False)
    op.create_index(op.f('ix__likes__event_id'), 'likes', ['event_id'], unique=False)
    op.create_index(op.f('ix__likes__user_id'), 'likes', ['user_id'], unique=False)
    op.create_index('likes_user_event_idx', 'likes', ['user_id', 'event_id'], unique=True)
    op.create_index(op.f('ix__participations__event_id'), 'participations', ['event_id'], unique=False)
    op.create_index(op.f('ix__participations__user_id'), 'participations', ['user_id'], unique=False)
    op.create_index('participations_user_event_idx', 'participations', ['user_id', 'event_id'], unique=True)
    op.create_index(op.f('ix__subscribed__event_id'), 'subscribed', ['event_id'], unique=False)
    op.create_index(op.f('ix__subscribed__user_id'), 'subscribed', ['user_id'], unique=False)
    op.create_index('subscribed_user_event_idx', 'subscribed', ['event_id', 'user_id'], unique=True)
    op.drop_constraint('uq__users__email', 'users', type_='unique')
    op.create_index(op.f('ix__users__email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__users__email'), table_name='users')
    op.create_unique_constraint('uq__users__email', 'users', ['email'])
    op.drop_index('subscribed_user_event_idx', table_name='subscribed')
    op.drop_index(op.f('ix__subscribed__user_id'), table_name='subscribed')
    op.drop_index(op.f('ix__subscribed__event_id'), table_name='subscribed')
    op.drop_index('participations_user_event_idx', table_name='participations')
    op.drop_index(op.f('ix__participations__user_id'), table_name='participations')
    op.drop_index(op.f('ix__participations__event_id'), table_name='participations')
    op.drop_index('likes_user_event_idx', table_name='likes')
    op.drop_index(op.f('ix__likes__user_id'), table_name='likes')
    op.drop_index(op.f('ix__likes__event_id'), table_name='likes')
    op.drop_index(op.f('ix__favourites__user_id'), table_name='favourites')
    op.drop_index(op.f('ix__favourites__event_id'), table_name='favourites')
    op.drop_index('favourites_user_event_idx', table_name='favourites')
    op.drop_index(op.f('ix__events__start_date'), table_name='events')
    op.drop_index(op.f('ix__events__reg_end_date'), table_name='events')
    op.drop_index(op.f('ix__events__event_type'), table_name='events')
    op.drop_index(op.f('ix__events__end_date'), table_name='events')
    op.drop_index(op.f('ix__events__creator_id'), table_name='events')
    op.drop_index(op.f('ix__events__category_type'), table_name='events')
    op.drop_index(op.f('ix__credentials__user_id'), table_name='credentials')
    op.drop_index('credentials_user_credential_type_idx', table_name='credentials')
    op.drop_index(op.f('ix__channels__creator_id'), table_name='channels')
    # ### end Alembic commands ###
