"""empty message

Revision ID: 28abbf03eaee
Revises: 73a0a62a3583
Create Date: 2023-01-18 14:21:29.852789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28abbf03eaee'
down_revision = '73a0a62a3583'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE eventtype AS ENUM ('SCOUT', 'TEENAGER', 'JUNIOR', 'FAMILY')")
    op.add_column('events', sa.Column('event_type', postgresql.ENUM('SCOUT', 'TEENAGER', 'JUNIOR', 'FAMILY', name='eventtype'), nullable=True))
    op.add_column('events', sa.Column('union_full', sa.String(), nullable=True))
    op.add_column('events', sa.Column('union_short', sa.String(), nullable=True))
    op.add_column('events', sa.Column('min_age', sa.INTEGER(), nullable=True))
    op.add_column('events', sa.Column('latitude', sa.FLOAT(), nullable=True))
    op.add_column('events', sa.Column('longitude', sa.FLOAT(), nullable=True))
    op.alter_column('events', 'total_places',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'total_places',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('events', 'longitude')
    op.drop_column('events', 'latitude')
    op.drop_column('events', 'min_age')
    op.drop_column('events', 'union_short')
    op.drop_column('events', 'union_full')
    op.drop_column('events', 'event_type')
    op.execute('drop type eventtype')
    # ### end Alembic commands ###
