"""empty message

Revision ID: ed0b3c8f1336
Revises: db85eb23bf88
Create Date: 2023-01-19 15:42:09.616030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0b3c8f1336'
down_revision = 'db85eb23bf88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('short_description', sa.String(), nullable=True))
    op.add_column('events', sa.Column('reg_end_date', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('events', sa.Column('max_age', sa.INTEGER(), nullable=True))
    op.create_unique_constraint(op.f('uq__unions__id'), 'unions', ['id'])
    op.add_column('users', sa.Column('parent_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'parent_phone')
    op.drop_constraint(op.f('uq__unions__id'), 'unions', type_='unique')
    op.drop_column('events', 'max_age')
    op.drop_column('events', 'reg_end_date')
    op.drop_column('events', 'short_description')
    # ### end Alembic commands ###
