"""empty message

Revision ID: e0eb44523cb3
Revises: 918ff0a16a29
Create Date: 2023-01-26 14:14:05.005015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0eb44523cb3'
down_revision = '918ff0a16a29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_fio', sa.String(), nullable=True))
    op.drop_column('users', 'parent_last_name')
    op.drop_column('users', 'parent_middle_name')
    op.drop_column('users', 'parent_first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('parent_middle_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('parent_last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'parent_fio')
    # ### end Alembic commands ###
