"""empty message

Revision ID: 918ff0a16a29
Revises: 193dc7674ad6
Create Date: 2023-01-25 15:10:02.442245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918ff0a16a29'
down_revision = '193dc7674ad6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('price', sa.NUMERIC(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'price')
    # ### end Alembic commands ###
