"""empty message

Revision ID: 5a844842cc3b
Revises: 28abbf03eaee
Create Date: 2023-01-19 13:39:16.379414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a844842cc3b'
down_revision = '28abbf03eaee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__credentials__user_id_credential_type'), 'credentials', ['user_id', 'credential_type'])
    op.create_unique_constraint(op.f('uq__users__email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__email'), 'users', type_='unique')
    op.drop_constraint(op.f('uq__credentials__user_id_credential_type'), 'credentials', type_='unique')
    # ### end Alembic commands ###
