"""empty message

Revision ID: 9a368348329f
Revises: 86d1e82afb57
Create Date: 2023-01-28 15:38:13.176147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from models.events import Visibility

# revision identifiers, used by Alembic.
revision = '9a368348329f'
down_revision = '86d1e82afb57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create type visibility as ENUM ('PUBLIC', 'PRIVATE')")
    op.add_column('events', sa.Column('visibility', postgresql.ENUM('PUBLIC', 'PRIVATE', name='visibility'), nullable=False, server_default=Visibility.PUBLIC))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'visibility')
    # ### end Alembic commands ###
