"""empty message

Revision ID: 63f9005b99d6
Revises: 615651da3942
Create Date: 2023-01-21 13:59:35.012328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f9005b99d6'
down_revision = '615651da3942'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
