"""empty message

Revision ID: 73a0a62a3583
Revises: 4478c045b868
Create Date: 2023-01-15 23:28:58.125609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a0a62a3583'
down_revision = '4478c045b868'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participations', sa.Column('payment_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participations', 'payment_id')
    # ### end Alembic commands ###
