"""empty message

Revision ID: ef1ad45732fa
Revises: ed0b3c8f1336
Create Date: 2023-01-19 15:42:20.421169

"""
from alembic import op
import sqlalchemy as sa
from models.unions import Unions

# revision identifiers, used by Alembic.
revision = 'ef1ad45732fa'
down_revision = 'ed0b3c8f1336'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    query = sa.insert(Unions).values(
        name='Северо западное объединение',
        short_name='СЗО'
    )
    session.execute(query)
    session.commit()
    query = sa.insert(Unions).values(
        name='Центральное объединение',
        short_name='ЦО'
    )
    session.execute(query)
    session.commit()
    query = sa.insert(Unions).values(
        name='Московское объединение',
        short_name='МО'
    )
    session.execute(query)
    session.commit()
    query = sa.insert(Unions).values(
        name='Волго-вятское объединение',
        short_name='ВВО'
    )
    session.execute(query)
    session.commit()
    query = sa.insert(Unions).values(
        name='Волжское объединение',
        short_name='ВО'
    )
    session.execute(query)
    session.commit()
    query = sa.insert(Unions).values(
        name='Уральское объединение',
        short_name='УО'
    )
    session.execute(query)
    session.commit()
    query = sa.insert(Unions).values(
        name='Южное объединение',
        short_name='ЮО'
    )
    session.execute(query)
    session.commit()
    query = sa.insert(Unions).values(
        name='Кубанско-черноморское объединение',
        short_name='КЧО'
    )
    session.execute(query)
    session.commit()
    query = sa.insert(Unions).values(
        name='Ростово-калмыцкое объединение',
        short_name='РКО'
    )
    session.execute(query)
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
