"""empty message

Revision ID: db85eb23bf88
Revises: 5a844842cc3b
Create Date: 2023-01-19 15:27:19.597695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db85eb23bf88'
down_revision = '5a844842cc3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unions',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__unions')),
    sa.UniqueConstraint('id', name=op.f('uq__unions__id')),
    sa.UniqueConstraint('name', name=op.f('uq__unions__name')),
    sa.UniqueConstraint('short_name', name=op.f('uq__unions__short_name'))
    )
    op.add_column('events', sa.Column('union_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk__events__union_id__unions'), 'events', 'unions', ['union_id'], ['id'], ondelete='SET NULL')
    op.drop_column('events', 'union_short')
    op.drop_column('events', 'union_full')
    op.add_column('users', sa.Column('union_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk__users__union_id__unions'), 'users', 'unions', ['union_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__users__union_id__unions'), 'users', type_='foreignkey')
    op.drop_column('users', 'union_id')
    op.add_column('events', sa.Column('union_full', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('union_short', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk__events__union_id__unions'), 'events', type_='foreignkey')
    op.drop_column('events', 'union_id')
    op.drop_table('unions')
    # ### end Alembic commands ###
