"""empty message

Revision ID: eb99eaff62b3
Revises: 63f9005b99d6
Create Date: 2023-01-21 16:25:30.121090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb99eaff62b3'
down_revision = '63f9005b99d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE colorvariant AS ENUM ('RED', 'ORANGE', 'YELLOW', 'GREEN', 'GRAY')")
    op.add_column('events', sa.Column('color_variant', postgresql.ENUM('RED', 'ORANGE', 'YELLOW', 'GREEN', 'GRAY', name='colorvariant'), nullable=False))
    op.drop_column('events', 'logo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('logo_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('events', 'color_variant')
    op.execute('drop type colorvariant')
    # ### end Alembic commands ###
