"""empty message

Revision ID: 4478c045b868
Revises: 28b2af9e8819
Create Date: 2023-01-14 22:30:22.402283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4478c045b868'
down_revision = '28b2af9e8819'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('url_link', sa.String(), nullable=True))
    op.drop_constraint('fk__events__channel_id__channels', 'events', type_='foreignkey')
    op.drop_column('events', 'channel_id')
    op.drop_column('events', 'available_places')
    op.drop_column('events', 'link')
    op.drop_column('events', 'rating')
    op.create_unique_constraint(op.f('uq__participations__id'), 'participations', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__participations__id'), 'participations', type_='unique')
    op.add_column('events', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('available_places', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('channel_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk__events__channel_id__channels', 'events', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('events', 'url_link')
    # ### end Alembic commands ###
