"""empty message

Revision ID: 6e0c726108f6
Revises: ef1ad45732fa
Create Date: 2023-01-19 23:51:02.253214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e0c726108f6'
down_revision = 'ef1ad45732fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE categorytype AS ENUM ('EVENT', 'CAMP')")
    op.add_column('events', sa.Column('category_type', postgresql.ENUM('EVENT', 'CAMP', name='categorytype'), nullable=False))
    op.alter_column('events', 'event_type',
               existing_type=postgresql.ENUM('SCOUT', 'TEENAGER', 'JUNIOR', 'FAMILY', name='eventtype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'event_type',
               existing_type=postgresql.ENUM('SCOUT', 'TEENAGER', 'JUNIOR', 'FAMILY', name='eventtype'),
               nullable=True)
    op.drop_column('events', 'category_type')
    op.execute('drop type categorytype')
    # ### end Alembic commands ###
