"""empty message

Revision ID: 86d1e82afb57
Revises: e0eb44523cb3
Create Date: 2023-01-26 21:44:42.219738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d1e82afb57'
down_revision = 'e0eb44523cb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("alter type participationstages add value 'NOT_PARTICIPATED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
