name: MyDeploy

on:
  push:
    branches:
      - main

jobs:
  Killall:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: touch private_key && echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
      - run: ssh -i private_key -o StrictHostKeyChecking=accept-new deployer@${{ secrets.SSH_HOST }}
      - run: ssh -i private_key deployer@${{ secrets.SSH_HOST }} 'cd ~/na-slet/backend-migrations; touch done'
